a="10"
b="20"
c=a+b
print(c)
# ABOVE STATEMENT EXECUTES AND GIVEN OUTPUT AS 1020
# IT TAKES THE VALUES AS STRING DATATYPES BECAUSE IT'S IN DOUBLE QUOTES
# TO RESOLVE THIS , CASTING IS USED (COVVERT 1 DT INTO OTHER DT)


a=int("10")
b=int("20")
c=a+b
print(c)
# IT'S PRINT THE ADDITION VALUE OF THE NUM
