name=input("Enter name:")
score=int(input("Enter score:"))
department=input("Enter department:")
print("My name is :",name)
print("My score is :",score/10,"/10")
print("My department is :", department)
